import { nanoid } from 'nanoid';
import { LuLayoutDashboard } from 'react-icons/lu';
import { VscFileSubmodule } from 'react-icons/vsc';
import { SiFiles } from 'react-icons/si';
import { FaUserFriends } from 'react-icons/fa';
import { TiInputCheckedOutline } from 'react-icons/ti';
import { PiFileXBold } from 'react-icons/pi';

export const workflowDropdowns = [
  'Music',
  'NextJS',
  'Tailwind',
  'TypeScript',
  'JavaScript',
  'React',
  'Python',
  'Django',
  'Redux',
  'Football',
  'Cricket',
  'Singing',
];

export const tableData = [
  {
    id: nanoid(),
    name: 'damilola odusola',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'Oluwasegun Barnabas',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'damilola odusola',
    date: '22/01/2023',
  },
  {
    id: nanoid(),
    name: 'oni damilola',
    date: '28/11/2024',
  },
  {
    id: nanoid(),
    name: 'Ajibade Esther',
    date: '10/04/2023',
  },
  {
    id: nanoid(),
    name: 'Anuoluwa Deborah',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'chidera daniel',
    date: '28/01/2022',
  },
  {
    id: nanoid(),
    name: 'chukwuemeka bright',
    date: '10/04/2023',
  },
  {
    id: nanoid(),
    name: 'abel bright',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'Oluwasegun Barnabas',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'damilola odusola',
    date: '22/01/2023',
  },
  {
    id: nanoid(),
    name: 'oni damilola',
    date: '28/11/2024',
  },
  {
    id: nanoid(),
    name: 'Ajibade Esther',
    date: '10/04/2023',
  },
  {
    id: nanoid(),
    name: 'Anuoluwa Deborah',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'chidera daniel',
    date: '28/01/2022',
  },
  {
    id: nanoid(),
    name: 'chukwuemeka bright',
    date: '10/04/2023',
  },
  {
    id: nanoid(),
    name: 'abel bright',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'Oluwasegun Barnabas',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'damilola odusola',
    date: '22/01/2023',
  },
  {
    id: nanoid(),
    name: 'oni damilola',
    date: '28/11/2024',
  },
  {
    id: nanoid(),
    name: 'Ajibade Esther',
    date: '10/04/2023',
  },
  {
    id: nanoid(),
    name: 'Anuoluwa Deborah',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'chidera daniel',
    date: '28/01/2022',
  },
  {
    id: nanoid(),
    name: 'chukwuemeka bright',
    date: '10/04/2023',
  },
  {
    id: nanoid(),
    name: 'abel bright',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'Oluwasegun Barnabas',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'damilola odusola',
    date: '22/01/2023',
  },
  {
    id: nanoid(),
    name: 'oni damilola',
    date: '28/11/2024',
  },
  {
    id: nanoid(),
    name: 'Ajibade Esther',
    date: '10/04/2023',
  },
  {
    id: nanoid(),
    name: 'Anuoluwa Deborah',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'chidera daniel',
    date: '28/01/2022',
  },
  {
    id: nanoid(),
    name: 'chukwuemeka bright',
    date: '10/04/2023',
  },
  {
    id: nanoid(),
    name: 'abel bright',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'Oluwasegun Barnabas',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'damilola odusola',
    date: '22/01/2023',
  },
  {
    id: nanoid(),
    name: 'oni damilola',
    date: '28/11/2024',
  },
  {
    id: nanoid(),
    name: 'Ajibade Esther',
    date: '10/04/2023',
  },
  {
    id: nanoid(),
    name: 'Anuoluwa Deborah',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'chidera daniel',
    date: '28/01/2022',
  },
  {
    id: nanoid(),
    name: 'chukwuemeka bright',
    date: '10/04/2023',
  },
  {
    id: nanoid(),
    name: 'abel bright',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'Oluwasegun Barnabas',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'damilola odusola',
    date: '22/01/2023',
  },
  {
    id: nanoid(),
    name: 'oni damilola',
    date: '28/11/2024',
  },
  {
    id: nanoid(),
    name: 'Ajibade Esther',
    date: '10/04/2023',
  },
  {
    id: nanoid(),
    name: 'Anuoluwa Deborah',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'chidera daniel',
    date: '28/01/2022',
  },
  {
    id: nanoid(),
    name: 'chukwuemeka bright',
    date: '10/04/2023',
  },
  {
    id: nanoid(),
    name: 'abel bright',
    date: '28/01/2023',
  },
];

export const secondTableData = [
  {
    id: nanoid(),
    name: 'damilola odusola',
    workflow: 'Music',
    stage: 'Pending',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'Oluwasegun Barnabas',
    date: '28/01/2023',
    workflow: 'css',
    stage: 'successful',
  },
  {
    id: nanoid(),
    name: 'damilola odusola',
    date: '22/01/2023',
    workflow: 'react',
    stage: 'cancelled',
  },
  {
    id: nanoid(),
    name: 'oni damilola',
    date: '28/11/2024',
    workflow: 'Music',
    stage: 'scheduled',
  },
  {
    id: nanoid(),
    name: 'Ajibade Esther',
    date: '10/04/2023',
    workflow: 'nextjs',
    stage: 'Pending',
  },
  {
    id: nanoid(),
    name: 'Anuoluwa Deborah',
    date: '28/01/2023',
    workflow: 'typescript',
    stage: 'Pending',
  },
  {
    id: nanoid(),
    name: 'chidera daniel',
    date: '28/01/2022',
    workflow: 'python',
    stage: 'waiting',
  },
  {
    id: nanoid(),
    name: 'chukwuemeka bright',
    date: '10/04/2023',
    workflow: 'redux',
    stage: 'Pending',
  },
  {
    id: nanoid(),
    name: 'abel bright',
    date: '28/01/2023',
    workflow: 'Music',
    stage: 'Pending',
  },
  {
    id: nanoid(),
    name: 'damilola odusola',
    workflow: 'Music',
    stage: 'Pending',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'Oluwasegun Barnabas',
    date: '28/01/2023',
    workflow: 'css',
    stage: 'successful',
  },
  {
    id: nanoid(),
    name: 'damilola odusola',
    date: '22/01/2023',
    workflow: 'react',
    stage: 'cancelled',
  },
  {
    id: nanoid(),
    name: 'oni damilola',
    date: '28/11/2024',
    workflow: 'Music',
    stage: 'scheduled',
  },
  {
    id: nanoid(),
    name: 'Ajibad esther',
    date: '10/04/2023',
    workflow: 'nextjs',
    stage: 'Pending',
  },
  {
    id: nanoid(),
    name: 'Anuoluwa Deborah',
    date: '28/01/2023',
    workflow: 'typescript',
    stage: 'Pending',
  },
  {
    id: nanoid(),
    name: 'chidera daniel',
    date: '28/01/2022',
    workflow: 'python',
    stage: 'waiting',
  },
  {
    id: nanoid(),
    name: 'chukwuemeka bright',
    date: '10/04/2023',
    workflow: 'redux',
    stage: 'Pending',
  },
  {
    id: nanoid(),
    name: 'abel bright',
    date: '28/01/2023',
    workflow: 'Music',
    stage: 'Pending',
  },
  {
    id: nanoid(),
    name: 'damilola odusola',
    workflow: 'Music',
    stage: 'Pending',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'Oluwasegun Barnabas',
    date: '28/01/2023',
    workflow: 'css',
    stage: 'successful',
  },
  {
    id: nanoid(),
    name: 'damilola odusola',
    date: '22/01/2023',
    workflow: 'react',
    stage: 'cancelled',
  },
  {
    id: nanoid(),
    name: 'oni damilola',
    date: '28/11/2024',
    workflow: 'Music',
    stage: 'scheduled',
  },
  {
    id: nanoid(),
    name: 'Ajibade esther',
    date: '10/04/2023',
    workflow: 'nextjs',
    stage: 'Pending',
  },
  {
    id: nanoid(),
    name: 'Anuoluwa Deborah',
    date: '28/01/2023',
    workflow: 'typescript',
    stage: 'Pending',
  },
  {
    id: nanoid(),
    name: 'chidera daniel',
    date: '28/01/2022',
    workflow: 'python',
    stage: 'waiting',
  },
  {
    id: nanoid(),
    name: 'chukwuemeka bright',
    date: '10/04/2023',
    workflow: 'redux',
    stage: 'Pending',
  },
  {
    id: nanoid(),
    name: 'abel bright',
    date: '28/01/2023',
    workflow: 'Music',
    stage: 'Pending',
  },
  {
    id: nanoid(),
    name: 'damilola odusola',
    workflow: 'Music',
    stage: 'Pending',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'Oluwasegun Barnabas',
    date: '28/01/2023',
    workflow: 'css',
    stage: 'successful',
  },
  {
    id: nanoid(),
    name: 'damilola odusola',
    date: '22/01/2023',
    workflow: 'react',
    stage: 'cancelled',
  },
  {
    id: nanoid(),
    name: 'oni damilola',
    date: '28/11/2024',
    workflow: 'Music',
    stage: 'scheduled',
  },
  {
    id: nanoid(),
    name: 'Ajibade esther',
    date: '10/04/2023',
    workflow: 'nextjs',
    stage: 'Pending',
  },
  {
    id: nanoid(),
    name: 'Anuoluwa Deborah',
    date: '28/01/2023',
    workflow: 'typescript',
    stage: 'Pending',
  },
  {
    id: nanoid(),
    name: 'chidera daniel',
    date: '28/01/2022',
    workflow: 'python',
    stage: 'waiting',
  },
  {
    id: nanoid(),
    name: 'chukwuemeka bright',
    date: '10/04/2023',
    workflow: 'redux',
    stage: 'Pending',
  },
  {
    id: nanoid(),
    name: 'abel bright',
    date: '28/01/2023',
    workflow: 'Music',
    stage: 'Pending',
  },
  {
    id: nanoid(),
    name: 'damilola odusola',
    workflow: 'Music',
    stage: 'Pending',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'Oluwasegun Barnabas',
    date: '28/01/2023',
    workflow: 'css',
    stage: 'successful',
  },
  {
    id: nanoid(),
    name: 'damilola odusola',
    date: '22/01/2023',
    workflow: 'react',
    stage: 'cancelled',
  },
  {
    id: nanoid(),
    name: 'oni damilola',
    date: '28/11/2024',
    workflow: 'Music',
    stage: 'scheduled',
  },
  {
    id: nanoid(),
    name: 'Ajibade esther',
    date: '10/04/2023',
    workflow: 'nextjs',
    stage: 'Pending',
  },
  {
    id: nanoid(),
    name: 'Anuoluwa Deborah',
    date: '28/01/2023',
    workflow: 'typescript',
    stage: 'Pending',
  },
  {
    id: nanoid(),
    name: 'chidera daniel',
    date: '28/01/2022',
    workflow: 'python',
    stage: 'waiting',
  },
  {
    id: nanoid(),
    name: 'chukwuemeka bright',
    date: '10/04/2023',
    workflow: 'redux',
    stage: 'Pending',
  },
  {
    id: nanoid(),
    name: 'abel bright',
    date: '28/01/2023',
    workflow: 'Music',
    stage: 'Pending',
  },
  {
    id: nanoid(),
    name: 'damilola odusola',
    workflow: 'Music',
    stage: 'Pending',
    date: '28/01/2023',
  },
  {
    id: nanoid(),
    name: 'Oluwasegun Barnabas',
    date: '28/01/2023',
    workflow: 'css',
    stage: 'successful',
  },
];

const sidebarContent = [
  {
    id: nanoid(),
    title: 'Dashboard',
    icon: <LuLayoutDashboard className="text-amber-300 text-xl" />,
  },
  {
    id: nanoid(),
    title: 'Document Collection',
    icon: <VscFileSubmodule className="text-amber-300 text-xl" />,
  },
  {
    id: nanoid(),
    title: 'Favorite Files',
    icon: <SiFiles className="text-amber-300 text-xl" />,
  },
  {
    id: nanoid(),
    title: 'Assigned to Me',
    icon: <FaUserFriends className="text-amber-300 text-xl" />,
  },
  {
    id: nanoid(),
    title: 'Checkout',
    icon: <TiInputCheckedOutline className="text-amber-300 text-xl" />,
  },
  {
    id: nanoid(),
    title: 'Unindexed Files',
    icon: <PiFileXBold className="text-amber-300 text-xl" />,
  },
];

export default sidebarContent;
